
# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

[window]

opacity = 0.85

padding.x = 1
padding.y = 1

decorations = "None"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "scientifica"
bold.family = "scientifica"
italic.family = "scientifica"
bold_italic.family = "scientifica"

size = 10.7

[colors.primary]

background = "#121619"



